name: S3 Media Sync Integration Tests

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  test:
    name: WP ${{ matrix.wordpress }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.3]
        wordpress: [5.9, latest]

    steps:
    - name: Install SVN (Subversion)
      run: |
        sudo apt-get update
        sudo apt-get install subversion

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Setup problem matchers for PHP
      run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

    - name: Setup Problem Matchers for PHPUnit
      run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install Composer dependencies
      uses: ramsey/composer-install@v3

    - name: Start MySQL Service
      run: sudo systemctl start mysql.service

    - name: Prepare environment for integration tests
      run: composer prepare-ci

    - name: Run integration tests (single site)
      if: ${{ matrix.php != 8.2 }}
      run: composer test
    - name: Run integration tests (single site with code coverage)
      if: ${{ matrix.php == 8.2 }}
      run: composer coverage-ci
    - name: Run integration tests (multisite)
      run: composer test-ms
